services:
  db: 
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${PISMO_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${PISMO_DATABASE_USER}
      POSTGRES_PASSWORD: ${PISMO_DATABASE_PASSWORD}
      POSTGRES_DB: ${PISMO_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local