// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package pgstore

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO account(
  document
)
values (
  $1
)
RETURNING id, document, created_at
`

func (q *Queries) CreateAccount(ctx context.Context, document string) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, document)
	var i Account
	err := row.Scan(&i.ID, &i.Document, &i.CreatedAt)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one

SELECT id, document, created_at FROM account
WHERE id = $1
`

func (q *Queries) GetAccountById(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountById, id)
	var i Account
	err := row.Scan(&i.ID, &i.Document, &i.CreatedAt)
	return i, err
}
