// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int32              `json:"id"`
	Document  string             `json:"document"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OperationsType struct {
	OperationTypeID int32  `json:"operation_type_id"`
	Description     string `json:"description"`
}

type Transaction struct {
	ID          int32            `json:"id"`
	AccountID   int32            `json:"account_id"`
	OperationID int32            `json:"operation_id"`
	Amount      pgtype.Numeric   `json:"amount"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
