// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transaction.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction(
  account_id,
  operation_id,
  amount
)
values(
  $1, -- account_id
  $2, -- operation_id
  $3  -- amount
)
RETURNING id, account_id, operation_id, amount, created_at
`

type CreateTransactionParams struct {
	AccountID   int32          `json:"account_id"`
	OperationID int32          `json:"operation_id"`
	Amount      pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.AccountID, arg.OperationID, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperationID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
