// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\artur\OneDrive\Documents\pismo\pismo-challenge\internal\services\account_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgstore "github.com/ArturLima/pismo/internal/store/pgstore"
	gomock "github.com/golang/mock/gomock"
)

// MockaccountQueries is a mock of accountQueries interface.
type MockaccountQueries struct {
	ctrl     *gomock.Controller
	recorder *MockaccountQueriesMockRecorder
}

// MockaccountQueriesMockRecorder is the mock recorder for MockaccountQueries.
type MockaccountQueriesMockRecorder struct {
	mock *MockaccountQueries
}

// NewMockaccountQueries creates a new mock instance.
func NewMockaccountQueries(ctrl *gomock.Controller) *MockaccountQueries {
	mock := &MockaccountQueries{ctrl: ctrl}
	mock.recorder = &MockaccountQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountQueries) EXPECT() *MockaccountQueriesMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockaccountQueries) CreateAccount(ctx context.Context, document string) (pgstore.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, document)
	ret0, _ := ret[0].(pgstore.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockaccountQueriesMockRecorder) CreateAccount(ctx, document interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockaccountQueries)(nil).CreateAccount), ctx, document)
}

// GetAccountById mocks base method.
func (m *MockaccountQueries) GetAccountById(ctx context.Context, id int32) (pgstore.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountById", ctx, id)
	ret0, _ := ret[0].(pgstore.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountById indicates an expected call of GetAccountById.
func (mr *MockaccountQueriesMockRecorder) GetAccountById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountById", reflect.TypeOf((*MockaccountQueries)(nil).GetAccountById), ctx, id)
}

// MockIAccountService is a mock of IAccountService interface.
type MockIAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountServiceMockRecorder
}

// MockIAccountServiceMockRecorder is the mock recorder for MockIAccountService.
type MockIAccountServiceMockRecorder struct {
	mock *MockIAccountService
}

// NewMockIAccountService creates a new mock instance.
func NewMockIAccountService(ctrl *gomock.Controller) *MockIAccountService {
	mock := &MockIAccountService{ctrl: ctrl}
	mock.recorder = &MockIAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountService) EXPECT() *MockIAccountServiceMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockIAccountService) CreateAccount(ctx context.Context, document string) (pgstore.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, document)
	ret0, _ := ret[0].(pgstore.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockIAccountServiceMockRecorder) CreateAccount(ctx, document interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockIAccountService)(nil).CreateAccount), ctx, document)
}

// GetAccount mocks base method.
func (m *MockIAccountService) GetAccount(ctx context.Context, accountId int32) (pgstore.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, accountId)
	ret0, _ := ret[0].(pgstore.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockIAccountServiceMockRecorder) GetAccount(ctx, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockIAccountService)(nil).GetAccount), ctx, accountId)
}
